// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/MeowSalty/pinai/database/types"
)

func newEndpoint(db *gorm.DB, opts ...gen.DOOption) endpoint {
	_endpoint := endpoint{}

	_endpoint.endpointDo.UseDB(db, opts...)
	_endpoint.endpointDo.UseModel(&types.Endpoint{})

	tableName := _endpoint.endpointDo.TableName()
	_endpoint.ALL = field.NewAsterisk(tableName)
	_endpoint.ID = field.NewInt64(tableName, "id")
	_endpoint.PlatformID = field.NewInt64(tableName, "platform_id")
	_endpoint.EndpointType = field.NewString(tableName, "endpoint_type")
	_endpoint.EndpointVariant = field.NewString(tableName, "endpoint_variant")
	_endpoint.Path = field.NewString(tableName, "path")
	_endpoint.CustomHeaders = field.NewField(tableName, "custom_headers")
	_endpoint.IsDefault = field.NewBool(tableName, "is_default")

	_endpoint.fillFieldMap()

	return _endpoint
}

type endpoint struct {
	endpointDo

	ALL             field.Asterisk
	ID              field.Int64
	PlatformID      field.Int64
	EndpointType    field.String
	EndpointVariant field.String
	Path            field.String
	CustomHeaders   field.Field
	IsDefault       field.Bool

	fieldMap map[string]field.Expr
}

func (e endpoint) Table(newTableName string) *endpoint {
	e.endpointDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e endpoint) As(alias string) *endpoint {
	e.endpointDo.DO = *(e.endpointDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *endpoint) updateTableName(table string) *endpoint {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.PlatformID = field.NewInt64(table, "platform_id")
	e.EndpointType = field.NewString(table, "endpoint_type")
	e.EndpointVariant = field.NewString(table, "endpoint_variant")
	e.Path = field.NewString(table, "path")
	e.CustomHeaders = field.NewField(table, "custom_headers")
	e.IsDefault = field.NewBool(table, "is_default")

	e.fillFieldMap()

	return e
}

func (e *endpoint) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *endpoint) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 7)
	e.fieldMap["id"] = e.ID
	e.fieldMap["platform_id"] = e.PlatformID
	e.fieldMap["endpoint_type"] = e.EndpointType
	e.fieldMap["endpoint_variant"] = e.EndpointVariant
	e.fieldMap["path"] = e.Path
	e.fieldMap["custom_headers"] = e.CustomHeaders
	e.fieldMap["is_default"] = e.IsDefault
}

func (e endpoint) clone(db *gorm.DB) endpoint {
	e.endpointDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e endpoint) replaceDB(db *gorm.DB) endpoint {
	e.endpointDo.ReplaceDB(db)
	return e
}

type endpointDo struct{ gen.DO }

type IEndpointDo interface {
	gen.SubQuery
	Debug() IEndpointDo
	WithContext(ctx context.Context) IEndpointDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEndpointDo
	WriteDB() IEndpointDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEndpointDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEndpointDo
	Not(conds ...gen.Condition) IEndpointDo
	Or(conds ...gen.Condition) IEndpointDo
	Select(conds ...field.Expr) IEndpointDo
	Where(conds ...gen.Condition) IEndpointDo
	Order(conds ...field.Expr) IEndpointDo
	Distinct(cols ...field.Expr) IEndpointDo
	Omit(cols ...field.Expr) IEndpointDo
	Join(table schema.Tabler, on ...field.Expr) IEndpointDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEndpointDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEndpointDo
	Group(cols ...field.Expr) IEndpointDo
	Having(conds ...gen.Condition) IEndpointDo
	Limit(limit int) IEndpointDo
	Offset(offset int) IEndpointDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEndpointDo
	Unscoped() IEndpointDo
	Create(values ...*types.Endpoint) error
	CreateInBatches(values []*types.Endpoint, batchSize int) error
	Save(values ...*types.Endpoint) error
	First() (*types.Endpoint, error)
	Take() (*types.Endpoint, error)
	Last() (*types.Endpoint, error)
	Find() ([]*types.Endpoint, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*types.Endpoint, err error)
	FindInBatches(result *[]*types.Endpoint, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*types.Endpoint) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEndpointDo
	Assign(attrs ...field.AssignExpr) IEndpointDo
	Joins(fields ...field.RelationField) IEndpointDo
	Preload(fields ...field.RelationField) IEndpointDo
	FirstOrInit() (*types.Endpoint, error)
	FirstOrCreate() (*types.Endpoint, error)
	FindByPage(offset int, limit int) (result []*types.Endpoint, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEndpointDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e endpointDo) Debug() IEndpointDo {
	return e.withDO(e.DO.Debug())
}

func (e endpointDo) WithContext(ctx context.Context) IEndpointDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e endpointDo) ReadDB() IEndpointDo {
	return e.Clauses(dbresolver.Read)
}

func (e endpointDo) WriteDB() IEndpointDo {
	return e.Clauses(dbresolver.Write)
}

func (e endpointDo) Session(config *gorm.Session) IEndpointDo {
	return e.withDO(e.DO.Session(config))
}

func (e endpointDo) Clauses(conds ...clause.Expression) IEndpointDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e endpointDo) Returning(value interface{}, columns ...string) IEndpointDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e endpointDo) Not(conds ...gen.Condition) IEndpointDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e endpointDo) Or(conds ...gen.Condition) IEndpointDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e endpointDo) Select(conds ...field.Expr) IEndpointDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e endpointDo) Where(conds ...gen.Condition) IEndpointDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e endpointDo) Order(conds ...field.Expr) IEndpointDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e endpointDo) Distinct(cols ...field.Expr) IEndpointDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e endpointDo) Omit(cols ...field.Expr) IEndpointDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e endpointDo) Join(table schema.Tabler, on ...field.Expr) IEndpointDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e endpointDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEndpointDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e endpointDo) RightJoin(table schema.Tabler, on ...field.Expr) IEndpointDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e endpointDo) Group(cols ...field.Expr) IEndpointDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e endpointDo) Having(conds ...gen.Condition) IEndpointDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e endpointDo) Limit(limit int) IEndpointDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e endpointDo) Offset(offset int) IEndpointDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e endpointDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEndpointDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e endpointDo) Unscoped() IEndpointDo {
	return e.withDO(e.DO.Unscoped())
}

func (e endpointDo) Create(values ...*types.Endpoint) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e endpointDo) CreateInBatches(values []*types.Endpoint, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e endpointDo) Save(values ...*types.Endpoint) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e endpointDo) First() (*types.Endpoint, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*types.Endpoint), nil
	}
}

func (e endpointDo) Take() (*types.Endpoint, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*types.Endpoint), nil
	}
}

func (e endpointDo) Last() (*types.Endpoint, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*types.Endpoint), nil
	}
}

func (e endpointDo) Find() ([]*types.Endpoint, error) {
	result, err := e.DO.Find()
	return result.([]*types.Endpoint), err
}

func (e endpointDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*types.Endpoint, err error) {
	buf := make([]*types.Endpoint, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e endpointDo) FindInBatches(result *[]*types.Endpoint, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e endpointDo) Attrs(attrs ...field.AssignExpr) IEndpointDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e endpointDo) Assign(attrs ...field.AssignExpr) IEndpointDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e endpointDo) Joins(fields ...field.RelationField) IEndpointDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e endpointDo) Preload(fields ...field.RelationField) IEndpointDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e endpointDo) FirstOrInit() (*types.Endpoint, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*types.Endpoint), nil
	}
}

func (e endpointDo) FirstOrCreate() (*types.Endpoint, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*types.Endpoint), nil
	}
}

func (e endpointDo) FindByPage(offset int, limit int) (result []*types.Endpoint, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e endpointDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e endpointDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e endpointDo) Delete(models ...*types.Endpoint) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *endpointDo) withDO(do gen.Dao) *endpointDo {
	e.DO = *do.(*gen.DO)
	return e
}
