// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/MeowSalty/pinai/database/types"
)

func newModel(db *gorm.DB, opts ...gen.DOOption) model {
	_model := model{}

	_model.modelDo.UseDB(db, opts...)
	_model.modelDo.UseModel(&types.Model{})

	tableName := _model.modelDo.TableName()
	_model.ALL = field.NewAsterisk(tableName)
	_model.ID = field.NewUint(tableName, "id")
	_model.PlatformID = field.NewUint(tableName, "platform_id")
	_model.Name = field.NewString(tableName, "name")
	_model.Alias_ = field.NewString(tableName, "alias")
	_model.Platform = modelBelongsToPlatform{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Platform", "types.Platform"),
	}

	_model.fillFieldMap()

	return _model
}

type model struct {
	modelDo

	ALL        field.Asterisk
	ID         field.Uint
	PlatformID field.Uint
	Name       field.String
	Alias_     field.String
	Platform   modelBelongsToPlatform

	fieldMap map[string]field.Expr
}

func (m model) Table(newTableName string) *model {
	m.modelDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m model) As(alias string) *model {
	m.modelDo.DO = *(m.modelDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *model) updateTableName(table string) *model {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.PlatformID = field.NewUint(table, "platform_id")
	m.Name = field.NewString(table, "name")
	m.Alias_ = field.NewString(table, "alias")

	m.fillFieldMap()

	return m
}

func (m *model) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *model) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 5)
	m.fieldMap["id"] = m.ID
	m.fieldMap["platform_id"] = m.PlatformID
	m.fieldMap["name"] = m.Name
	m.fieldMap["alias"] = m.Alias_

}

func (m model) clone(db *gorm.DB) model {
	m.modelDo.ReplaceConnPool(db.Statement.ConnPool)
	m.Platform.db = db.Session(&gorm.Session{Initialized: true})
	m.Platform.db.Statement.ConnPool = db.Statement.ConnPool
	return m
}

func (m model) replaceDB(db *gorm.DB) model {
	m.modelDo.ReplaceDB(db)
	m.Platform.db = db.Session(&gorm.Session{})
	return m
}

type modelBelongsToPlatform struct {
	db *gorm.DB

	field.RelationField
}

func (a modelBelongsToPlatform) Where(conds ...field.Expr) *modelBelongsToPlatform {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a modelBelongsToPlatform) WithContext(ctx context.Context) *modelBelongsToPlatform {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a modelBelongsToPlatform) Session(session *gorm.Session) *modelBelongsToPlatform {
	a.db = a.db.Session(session)
	return &a
}

func (a modelBelongsToPlatform) Model(m *types.Model) *modelBelongsToPlatformTx {
	return &modelBelongsToPlatformTx{a.db.Model(m).Association(a.Name())}
}

func (a modelBelongsToPlatform) Unscoped() *modelBelongsToPlatform {
	a.db = a.db.Unscoped()
	return &a
}

type modelBelongsToPlatformTx struct{ tx *gorm.Association }

func (a modelBelongsToPlatformTx) Find() (result *types.Platform, err error) {
	return result, a.tx.Find(&result)
}

func (a modelBelongsToPlatformTx) Append(values ...*types.Platform) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a modelBelongsToPlatformTx) Replace(values ...*types.Platform) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a modelBelongsToPlatformTx) Delete(values ...*types.Platform) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a modelBelongsToPlatformTx) Clear() error {
	return a.tx.Clear()
}

func (a modelBelongsToPlatformTx) Count() int64 {
	return a.tx.Count()
}

func (a modelBelongsToPlatformTx) Unscoped() *modelBelongsToPlatformTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type modelDo struct{ gen.DO }

type IModelDo interface {
	gen.SubQuery
	Debug() IModelDo
	WithContext(ctx context.Context) IModelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IModelDo
	WriteDB() IModelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IModelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IModelDo
	Not(conds ...gen.Condition) IModelDo
	Or(conds ...gen.Condition) IModelDo
	Select(conds ...field.Expr) IModelDo
	Where(conds ...gen.Condition) IModelDo
	Order(conds ...field.Expr) IModelDo
	Distinct(cols ...field.Expr) IModelDo
	Omit(cols ...field.Expr) IModelDo
	Join(table schema.Tabler, on ...field.Expr) IModelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IModelDo
	RightJoin(table schema.Tabler, on ...field.Expr) IModelDo
	Group(cols ...field.Expr) IModelDo
	Having(conds ...gen.Condition) IModelDo
	Limit(limit int) IModelDo
	Offset(offset int) IModelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IModelDo
	Unscoped() IModelDo
	Create(values ...*types.Model) error
	CreateInBatches(values []*types.Model, batchSize int) error
	Save(values ...*types.Model) error
	First() (*types.Model, error)
	Take() (*types.Model, error)
	Last() (*types.Model, error)
	Find() ([]*types.Model, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*types.Model, err error)
	FindInBatches(result *[]*types.Model, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*types.Model) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IModelDo
	Assign(attrs ...field.AssignExpr) IModelDo
	Joins(fields ...field.RelationField) IModelDo
	Preload(fields ...field.RelationField) IModelDo
	FirstOrInit() (*types.Model, error)
	FirstOrCreate() (*types.Model, error)
	FindByPage(offset int, limit int) (result []*types.Model, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IModelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m modelDo) Debug() IModelDo {
	return m.withDO(m.DO.Debug())
}

func (m modelDo) WithContext(ctx context.Context) IModelDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m modelDo) ReadDB() IModelDo {
	return m.Clauses(dbresolver.Read)
}

func (m modelDo) WriteDB() IModelDo {
	return m.Clauses(dbresolver.Write)
}

func (m modelDo) Session(config *gorm.Session) IModelDo {
	return m.withDO(m.DO.Session(config))
}

func (m modelDo) Clauses(conds ...clause.Expression) IModelDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m modelDo) Returning(value interface{}, columns ...string) IModelDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m modelDo) Not(conds ...gen.Condition) IModelDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m modelDo) Or(conds ...gen.Condition) IModelDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m modelDo) Select(conds ...field.Expr) IModelDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m modelDo) Where(conds ...gen.Condition) IModelDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m modelDo) Order(conds ...field.Expr) IModelDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m modelDo) Distinct(cols ...field.Expr) IModelDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m modelDo) Omit(cols ...field.Expr) IModelDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m modelDo) Join(table schema.Tabler, on ...field.Expr) IModelDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m modelDo) LeftJoin(table schema.Tabler, on ...field.Expr) IModelDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m modelDo) RightJoin(table schema.Tabler, on ...field.Expr) IModelDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m modelDo) Group(cols ...field.Expr) IModelDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m modelDo) Having(conds ...gen.Condition) IModelDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m modelDo) Limit(limit int) IModelDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m modelDo) Offset(offset int) IModelDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m modelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IModelDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m modelDo) Unscoped() IModelDo {
	return m.withDO(m.DO.Unscoped())
}

func (m modelDo) Create(values ...*types.Model) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m modelDo) CreateInBatches(values []*types.Model, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m modelDo) Save(values ...*types.Model) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m modelDo) First() (*types.Model, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*types.Model), nil
	}
}

func (m modelDo) Take() (*types.Model, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*types.Model), nil
	}
}

func (m modelDo) Last() (*types.Model, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*types.Model), nil
	}
}

func (m modelDo) Find() ([]*types.Model, error) {
	result, err := m.DO.Find()
	return result.([]*types.Model), err
}

func (m modelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*types.Model, err error) {
	buf := make([]*types.Model, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m modelDo) FindInBatches(result *[]*types.Model, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m modelDo) Attrs(attrs ...field.AssignExpr) IModelDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m modelDo) Assign(attrs ...field.AssignExpr) IModelDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m modelDo) Joins(fields ...field.RelationField) IModelDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m modelDo) Preload(fields ...field.RelationField) IModelDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m modelDo) FirstOrInit() (*types.Model, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*types.Model), nil
	}
}

func (m modelDo) FirstOrCreate() (*types.Model, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*types.Model), nil
	}
}

func (m modelDo) FindByPage(offset int, limit int) (result []*types.Model, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m modelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m modelDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m modelDo) Delete(models ...*types.Model) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *modelDo) withDO(do gen.Dao) *modelDo {
	m.DO = *do.(*gen.DO)
	return m
}
