name: CI Build

on:
  push:
    branches:
      - "**" # 所有分支上的推送都会触发

env:
  REPO_LC: ${{ github.repository }}
  CI_TAG: CI_TAG

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare environment
        run: |
          echo "REPO_LC=${REPO_LC,,}" >> ${GITHUB_ENV}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate CI tag
        id: generate-tag
        run: |
          TIMESTAMP=$(date -u +"%Y%m%d-%H%M")
          SHORT_SHA=$(git rev-parse --short HEAD)
          CI_TAG="ci-${TIMESTAMP}-g${SHORT_SHA}"
          echo "CI_TAG=$CI_TAG" >> $GITHUB_ENV
          echo "Generated CI tag: $CI_TAG"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ env.REPO_LC }}:${{ env.CI_TAG }}
            ghcr.io/${{ env.REPO_LC }}:ci-latest
          push: true
          build-args: |
            VERSION=${{ env.CI_TAG }}