name: Daily Build

on:
  schedule:
    # 每天 UTC 时间 20 点运行 (即北京时间 4 点)
    - cron: "0 20 * * *"
  workflow_dispatch: # 允许手动触发

env:
  REPO_LC: ${{ github.repository }}

jobs:
  build-docker-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Update portal dependency to main branch
        run: |
          go get github.com/MeowSalty/portal@main
          go mod tidy

      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
          echo "REPO_LC=${REPO_LC,,}" >> ${GITHUB_ENV}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.REPO_LC }}
          tags: |
            type=raw,value=daily-latest
            type=raw,value=daily-{{date 'YYYY-MM-DD' tz='Asia/Shanghai'}}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          build-args: |
            VERSION=daily-{{date 'YYYY-MM-DD'}}

  merge-docker-manifest:
    name: Merge Docker Manifest
    needs:
      - build-docker-images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Convert repository name to lowercase
        run: |
          echo "REPO_LC=${REPO_LC,,}" >> ${GITHUB_ENV}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.REPO_LC }}
          tags: |
            type=raw,value=daily-latest
            type=raw,value=daily-{{date 'YYYY-MM-DD' tz='Asia/Shanghai'}}

      - name: Create manifest list and push
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            ghcr.io/${{ env.REPO_LC }}:daily-latest

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ghcr.io/${{ env.REPO_LC }}:daily-latest